{
 "title": "ftps",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Rad usage gauge",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "docker_container_mem",
     "query": "SELECT mean(\"usage\") FROM \"docker_container_mem\" WHERE (\"app\" = \"$instamce\") AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "usage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "app", "operator": "=", "value": "ftps" }
     ]
    }
   ]
  },
  {
   "title": "Uptime minutes",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 6, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "docker_container_status",
     "select": [
      [
       { "params": [ "uptime_ns" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 60000000000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "app", "operator": "=", "value": "ftps" }
     ]
    }
   ]
  },
  {
   "title": "Neat network graph",
   "type": "stat",
   "gridPos": { "h": 10, "w": 12, "x": 11, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "docker_container_net",
     "select": [
      [
       { "params": [ "rx_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "integral"
       },
       {
        "params": [
         10
        ],
        "type": "moving_average"
       }
      ]
     ],
     "tags": [
      { "key": "app", "operator": "=", "value": "ftps" }
     ]
    }
   ]
  },
  {
   "title": "Cool cpu graph",
   "type": "graph",
   "description": "Mysql",
   "gridPos": { "h": 16, "w": 11, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "docker_container_cpu",
     "query": "SELECT mean(\"usage_percent\") FROM \"docker_container_cpu\" WHERE (\"container_name\" = 'k8s_mysql-container_mysql-deploy-78cfc47f99-fclhj_default_fa9789e0-a201-4096-8ddb-39087a7a5eec_0') AND $timeFilter GROUP BY time(10s) fill(null)",
     "select": [
      [
       { "params": [ "usage_total" ], "type": "field" },
       {
        "params": [],
        "type": "integral"
       }
      ]
     ],
     "tags": [
      { "key": "app", "operator": "=", "value": "ftps" }
     ]
    }
   ]
  },
  {
   "title": "Totally informative system usage",
   "type": "graph",
   "gridPos": { "h": 16, "w": 12, "x": 11, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "docker_container_cpu",
     "select": [
      [
       { "params": [ "usage_system" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "app", "operator": "=", "value": "ftps" }
     ]
    }
   ]
  }
 ]
}